### ISSUE TITLE
Issue in Generic Set Data Structure

### ISSUE THREAD

**Issue by ariz-ansari-tft** [arizansari80/My-Custom-C-Library#1]
there is issue in creating a Set of structure having variable size i.e. a set of structure that contains pointer. Can you please provide me a sample of creating set of structure that contains pointer

**Comment by arizansari80** [comment]
Please take clone of the master branch and build on Code Block IDE and run the following code
![Screenshot from 2021-01-16 11-16-02](https://user-images.githubusercontent.com/17806894/104798367-45360a80-57ec-11eb-8752-973da97ac157.png)


/*
 * s_main.c
 *
 *  Created on: 16-Jan-2021
 *      Author: arizansari80
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sets.h"
#include "c_string.h"

typedef struct student {
    int rollNumber;
    string name;
}student;

long double student_compare(const void *P1, const void *P2)
{
    student p1 = *(student *)P1;
    student p2 = *(student *)P2;
    if (p1.rollNumber == p2.rollNumber)
        return 0;
    return p1.rollNumber - p2.rollNumber;
}

void student_display(const void *P)
{
    student p = *(student *)P;
    printf("Name : %s",p.name);
    printf("Roll No. : %d", p.rollNumber);
}

extern const GLOBAL_STRING_OBJECT String;
extern const GLOBAL_SET_OBJECT Set;

int main(int argc, char *args[]) {
    set structSet;
    structSet = Set.getSet(sizeof(student), student_compare, student_display);
    int startRoll = 123;
    string name;
    for (int i = 0; i < 5; i++) {
        printf("Enter Name : ");
        name = String.getString();
        student *s = malloc(sizeof(student));
        s->rollNumber = startRoll++;
        s->name = malloc(sizeof(char) * strlen(name));
        strcpy(s->name,name);
        Set.addInSet(&structSet,s);
    }

    Set.printSet(structSet);
    Set.clearSet(&structSet);

    return 0;
}
